config/routes.rb
Rails.application.routes.draw do
  root "ten_years#index"

  resources :top do
  end

  resources :members do
    collection do
      get :login
      get :get_show_csv
      get :unsbscribe
      get :password_reset
    end
  end

  resources :consts do
  end

  resources :ages do
  end

  resources :prefectures do
  end

  resource :session, only: [:create, :destroy]

  resources :events do
    collection do
      get :year_new
      post :year_create
      get :destroy_all
      get :search
      get :set_mamber_filter
      get :restor_default
    end
  end

  resources :event_ages do
  end

  resources :event_prefectures do
  end

  resources :event_year_ages do
  end

  resources :csvs do
    collection do
      get :make_csv
      get :search
      get :set_target_csv
      get :delete_target_csv
      get :color_change
      get :show_data
      get :stop_open
    end
  end

  resources :ten_years do
    collection do
      get :login # ログイン画面
      get :detail
      get :manual
    end
  end

  resources :admins do
    collection do
      get :login # ログイン画面
    end
  end

  resources :session_admins, only: [:create, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  #年月日
  validates :date, presence: true
  #タイトル
  validates :title, presence: true, length: {maximum: 25}
  #詳細
  validates :detail, length: {maximum: 200}
  #人口増減
  validates :population_change, presence: true,
    numericality: {
      only_integer: true,
      greater_than: -10000000000,
      less_than:     10000000000
  }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :login_required

  def index
    #管理者かどうか
    @admin_flg = session[:member_admin]

    if @admin_flg

      #メンバーフィルタ作成
      @members = Member.pluck(:name, :id)
      @members.unshift("") #先頭に空データ追加

      #セッションに格納してあるフィルターID取得
      if session[:filter_member_id] == nil || session[:filter_member_id] == ''
        #全出来事を取得
        @events = Event.order("member_id", "date")
      else
        #該当メンバのデータのみ取得
        @events = Event.where(member_id: session[:filter_member_id]).order("date")
      end

    else
      #一般メンバーの場合、自分の出来事だけ取得
      @events = Event.where(member_id: session[:member_id]).order("date")
    end

    #イベントが1件もない場合、以降の処理を実施しない
    if !@events.present?
      return
    end

    #2011-01-01のレコードがあるか確認
    @is_exists_first_day = false
    if @events[0].date.to_s == "2011-01-01"
      @is_exists_first_day = true
    end

  end

  # 詳細表示
  def show
    @event = Event.find(params[:id])

    #該当イベントがsessionに格納されているユーザーIDと同じか確認。
    #違ったら一覧画面にリダイレクト
    if !session[:member_admin] && @event.member_id != session[:member_id]
      #一覧画面へリダイレクト
      redirect_to action: 'index'
      return
    end

    #event_agesTBLに出来事に紐づくデータがあるか探す
    @event_age = EventAge.find_by(event_id: params[:id])
    #event_prefectureTBLに出来事に紐づくデータがあるか探す
    @event_prefecture = EventPrefecture.find_by(event_id: params[:id])

    #50%沈没都道府県を日本語変換
    #カンマ区切り都道府県をリスト化
    @half_prefectures = ""
    if @event.half_sinking != nil
      @half_prefectures = get_prefecture_str(@event.half_sinking)
    end

    #沈没都道府県を日本語変換
    #カンマ区切り都道府県をリスト化
    @prefectures = ""
    if @event.sinking != nil
      @prefectures = get_prefecture_str(@event.sinking)
    end

    #一部汚染都道府県を日本語変換
    #カンマ区切り都道府県をリスト化
    @half_pollution = ""
    if @event.half_pollution != nil
      @half_pollution = get_prefecture_str(@event.half_pollution)
    end

    #全域汚染都道府県を日本語変換
    #カンマ区切り都道府県をリスト化
    @pollution = ""
    if @event.pollution != nil
      @pollution = get_prefecture_str(@event.pollution)
    end

    #前へ/次へボタン作成
    #まずは全イベントを日付順で取得
    if @admin_flg
      #管理者の場合、全出来事を取得
      @events = Event.order("member_id", "date")
    else
      #一般メンバーの場合、自分の出来事だけ取得
      @events = Event.where(member_id: session[:member_id]).order("date")
    end
    #全イベントでループし、前のIDと次のIDを取得
    @events.each_with_index do |event_wk, i|
      if event_wk.id.to_s == params[:id]
        #最初のデータの場合、beforeでは前ではなく表示している出来事へ遷移させる
        if i == 0
          @event_before = @events[i]
        else
          @event_before = @events[i - 1]
        end

        #最後のデータの場合、nextでは次ではなく表示している出来事へ遷移させる
        if i == @events.length-1
          @event_next = @events[i]
        else
          @event_next = @events[i + 1]
        end

        break
      end
    end

    #管理者フラグ取得
    @admin_flg = session[:member_admin]

  end

  #都道府県スラッシュ区切り取得
  def get_prefecture_str(str)
    #末尾にカンマがあるので削除
    @wk_str = str.chop
    @wk_arr = @wk_str.split(",")
    wk = ""
    @wk_arr.each do |prefecture_code|
      #都道府県日本語名を取得
      @prefecture_jpn = convert_prefecture(prefecture_code)
      #画面表示用文字列生成
      if wk.blank?
        wk = @prefecture_jpn
      else
        wk = wk + " / " + @prefecture_jpn
      end
    end
    return wk
  end

  def new
    @event = Event.new()
    #初期値設定
    @event.is_fake = false
    @event.is_active = true
    @event.population_change = 0
    @event.date = "2011-01-01"

    #管理者の場合のみ、メンバーリスト取得
    @admin_flg = session[:member_admin]
    if @admin_flg
      @members = Member.pluck(:name, :id)
    end
  end

  def create
    @event = Event.new(events_params)
    @event.event_type = 0
    @event.member_id = session[:member_id]

    #管理者でない場合のみ、デフォルトフラグをfalseに
    @admin_flg = session[:member_admin]
    if !@admin_flg
      @event.delault_flg = false
    end

    if @event.save
      redirect_to action: 'index'
    else
      if @admin_flg
        @members = Member.pluck(:name, :id)
      end
      render 'new'
    end
  end

  #更新
  def edit
    @event = Event.find(params[:id])

    #該当イベントがsessionに格納されているユーザーIDと同じか確認。
    #違ったら一覧画面にリダイレクト
    if !session[:member_admin] && (!@event.present? || @event.member_id != session[:member_id])
      #一覧画面へリダイレクト
      redirect_to action: 'index'
      return
    end

    #管理者の場合のみ、メンバーリスト取得
    @admin_flg = session[:member_admin]
    if @admin_flg
      @members = Member.pluck(:name, :id)

      #該当イベントの所有メンバーを先頭にする
      @members.each do |member|
        if member[1] == @event.member_id
          @members.delete(member) #まずは該当要素を削除
          @members.unshift(member) #先頭に要素を追加
          break
        end
      end
    end
  end

  def update
    @event = Event.find(params[:id])
    @event.assign_attributes(events_params)
    #人口増減に値がない場合、0を入れる
    if @event.population_change == nil || @event.population_change == ""
      @event.population_change = 0
    end

    #管理者の場合のみ、member_id更新機能アリ
    admin_flg = session[:member_admin]
    if admin_flg
      @event.member_id = params[:member_id]
    end

    if @event.save
      #犠牲者が0の場合、紐づくevent_ageのレコードも削除する
      if @event.population_change == 0
        con = ActiveRecord::Base.connection
        $q = "DELETE FROM event_ages WHERE event_id=" << params[:id]
        con.execute($q)
      end
      redirect_to event_path
    else
      render "edit"
    end
  end

  def destroy
    con = ActiveRecord::Base.connection
    # イベント、年齢男女別犠牲者、都道府県別犠牲者を削除
    $q1 = "DELETE FROM events WHERE id=" << (params[:id])
    con.execute($q1)
    $q2 = "DELETE FROM event_ages WHERE event_id=" << (params[:id])
    con.execute($q2)
    $q3 = "DELETE FROM event_prefectures WHERE event_id=" << (params[:id])
    con.execute($q3)

    #一覧画面へリダイレクト
    redirect_to action: 'index'
  end

  #年間人口増減登録
  def year_new
    #adminでない場合、indexにリダイレクト
    if !session[:member_admin]
      redirect_to events_path()
    end

    @event = Event.new()
    #初期値設定
    @event.date = "2011-12-31"
  end

  def year_create
    @event = Event.new(events_params)
    #自動的に登録する値を設定
    @event.event_type = 1
    @event.is_fake = false
    @event.is_active = true
    @event.population_change = 9999
    @event.delault_flg = true
    @event.member_id = session[:member_id]

    @event.title = "年間人口増減 " + @event.date.year.to_s
    @event.detail = "年間人口増減"

    #既に同年の年間人口増減が存在する場合（デフォルトに限る！）、以前のものを削除する
    con = ActiveRecord::Base.connection
    $q = "DELETE FROM events WHERE delault_flg = true and event_type = \"1\" and date =\"" << @event.date.to_s << "\""
    con.execute($q)

    if @event.save
      redirect_to action: 'index'
    else
      render 'year_new'
    end
  end

  # タイプの値取得
  def get_value_type(type)
    if type == 0
      return "出来事"
    end
    return "年間"
  end

  # フラグの値取得
  def get_flg_value(is_fake)
    if is_fake == false
      return "-"
    end
    return "○"
  end

  #男女・年齢別増減が正しく登録されているか
  def exist_event_data(id, db_neme)
    #該当イベント情報取得
    @event = Event.find(id)

    #人口総増減が0でない場合、以下の処理実施
    if @event.population_change != 0

      #該当イベントに紐づくレコードが該当DBに存在するか
      if db_neme == "event_age"
        @target = EventAge.find_by(event_id: id)
      else
        @target = EventPrefecture.find_by(event_id: id)
      end
      #存在しない場合
      if !@target.present?
        return set_puls(@event.population_change)
        #return "none"
      end

      if @event.population_change != @target.total
        #存在するが増減数に差異がある場合、"差異あり"を返却
        diff = @event.population_change - @target.total
        return set_puls(diff)
        #return "difference"
      else
        #正しい場合
        return "±0"
        #return "correct"
      end

    else
      #人口総増減が0の場合、居住地別人口で人の移動が存在するか確認
      if db_neme == "event_age"
        @target = EventAge.find_by(event_id: id)
      else
        @target = EventPrefecture.find_by(event_id: id)
      end

      #存在しない場合
      if !@target.present?
        return "±0"
        #return "unnecessary"
      else
        if @target.total == 0
          return "±0"
          #return "correct"
        else
          diff = @event.population_change - @target.total
          return set_puls(diff)
          #return "difference"
        end
      end
    end
    return "±0"
    #return "unnecessary"
  end

  #整数の頭に「＋」を加える
  def set_puls(num)
    if 0 < num
      return "+" + num.to_s
    end
    return num
  end

  # 有効でない出来事にグレーアウト用クラスを返却
  def get_row_class(event)
    if !available_event(event, true)
      return "gray_out"
    end
    return ""
  end

  # 有効な出来事か確認
  # フラグがfalseの場合、2011-01-01のレコード確認をしない
  def available_event(event, first_dat_chk_flg)

    #2011-01-01のレコードがあるか確認
    if first_dat_chk_flg
      if !@is_exists_first_day
        return false
      end
    end

    #無効の場合、false
    if !event.is_active
      return false
    end

    #event_ageTBLが不正の場合、false
    @wk = exist_event_data(event.id, "event_age")
    #if @wk == "none" || @wk == "difference"
    if @wk != "±0"
      return false
    end

    #event_prefectureTBLが不正の場合、false
    @wk = exist_event_data(event.id, "event_prefecture")
    #if @wk == "none" || @wk == "difference"
    if @wk != "±0"
      return false
    end

    return true
  end

  #沈没都道府県名変換
  def convert_prefecture(prefecture_code)
    case prefecture_code
    when "1-Hokkaido" then
      return "北海道"
    when "2-Aomori" then
      return "青森県"
    when "3-Iwate" then
      return "岩手県"
    when "4-Akita" then
      return "秋田県"
    when "5-Miyagi" then
      return "宮城県"
    when "6-Yamagata" then
      return "山形県"
    when "7-Fukushima" then
      return "福島県"
    when "8-Ibaraki" then
      return "茨城県"
    when "9-Tochigi" then
      return "栃木県"
    when "10-Gunma" then
      return "群馬県"
    when "11-Saitama" then
      return "埼玉県"
    when "12-Chiba" then
      return "千葉県"
    when "13-Tokyo" then
      return "東京都"
    when "14-Kanagawa" then
      return "神奈川県"
    when "15-Niigata" then
      return "新潟県"
    when "16-Toyama" then
      return "富山県"
    when "17-Ishikawa" then

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/new.html.erb
<%= render "form" %>

app/views/events/show.html.erb
<div class="body">
  <div class="div_center">
    <div class="div_bold">■出来事情報画面■</div><br/>
    <div>
      <% if @admin_flg %>
        管理者専用 メンバーID: <%= @event.member_id %>
        <br/>
      <% end %>

      <div>
        <%= link_to "前へ", @event_before, :class=>'no_border_link side_margin' %>
        <%= link_to "次へ", @event_next, :class=>'no_border_link side_margin' %>
      </div>

      <% if @event.event_type == 0 %>
        <span class="side_margin">
          <%= link_to "編集", :edit_event, :class=>'no_border_link' %>
        </span>
        <% if @event_age.present? %>
          <span class="side_margin">
            <%= link_to "[編集]性別・年齢別人口増減", edit_event_age_path(event_id: @event.id), :class=>'no_border_link' %>
          </span>
        <% else %>
          <span class="side_margin">
            <%= link_to "[登録]性別・年齢別人口増減", new_event_age_path(event_id: @event.id), :class=>'no_border_link' %>
          </span>
        <% end %>

      <% elsif @event.event_type == 1 %>
        <% if @admin_flg %>
          <%= link_to "編集", :edit_event, :class=>'no_border_link' %>
        <% end %>
        <% if @event_age.present? %>
          <span class="side_margin">
            <%= link_to "[編集]性別・年齢別年間人口増減", edit_event_year_age_path(event_id: @event.id), :class=>'no_border_link' %>
          </span>
        <% else %>
          <span class="side_margin">
            <%= link_to "[登録]性別・年齢別年間人口増減", new_event_year_age_path(event_id: @event.id), :class=>'no_border_link' %>
          </span>
        <% end %>
      <% end %>

      <% if @event_prefecture.present? %>
        <span class="side_margin">
          <%= link_to "[編集]居住地別人口増減・移動", edit_event_prefecture_path(event_id: @event.id), :class=>'no_border_link' %>
        </span>
      <% else %>
        <span class="side_margin">
          <%= link_to "[登録]居住地別人口増減・移動", new_event_prefecture_path(event_id: @event.id), :class=>'no_border_link' %>
        </span>
      <% end %>

      <% if @admin_flg || (@event.event_type == 0 && controller.check_first_data(@event) ) %>
        <span class="side_margin">
          <%= link_to "削除", "#{@event.id}", method: :delete,
            data: {confirm: "性別・年齢別人口増減と居住地別人口増減・移動も同時に削除されます。よろしいですか?"}, :class=>'no_border_link'%>
        </span>
      <% end %>

      <% if !@admin_flg && @event.event_type == 1 %>
        <span class="side_margin">
          <%= link_to "初期値復元", restor_default_events_url(id: @event.id ,title: @event.title),
            data: {confirm: "ご自身で入力したデータが失われます。よろしいですか?"}, :class=>'no_border_link'%>
        </span>
      <% end %>

    </div>

    <div class="font_20"><%= @event.title %></div>
    <table id="age_new_table" class="table_main inline-block">
      <tr>
        <td colspan="2">
          <span class="div_bold">日付</span>:<%= @event.date %> |
          <span class="div_bold">総人口増減</span>:<%= @event.population_change %> |
          <span class="div_bold">フィクション</span>:<%= controller.get_flg_value(@event.is_fake) %> |
          <span class="div_bold">有効</span>:<%= controller.get_flg_value(@event.is_active) %>
        </td>
      </tr>
      <tr>
        <th class="">詳細</th>
        <td class="td_w500 div_left"><%= simple_format(@event.detail) %></td>
      </tr>
      <tr>
        <th class="">一部汚染都道府県</th>
        <td class="div_left"><%= @half_pollution %></td>
      </tr>
      <tr>
        <th class="">全域汚染都道府県</th>
        <td class="div_left"><%= @pollution %></td>
      </tr>
      <tr>
        <th class="">一部沈没都道府県</th>
        <td class="div_left"><%= @half_prefectures %></td>
      </tr>
      <tr>
        <th class="">全域沈没都道府県</th>
        <td class="div_left"><%= @prefectures %></td>
      </tr>
    </table>

    <%# 男女年齢別begin　%>
    <% if @event_age.present? %>
    <div><span class="div_bold">性別・年齢別人口増減</span></div>
      <table class="table_main inline-block head_color">
        <thead>
          <tr>
            <th class="td_w100">女性<span class="font_12"></span></th>
            <th class="td_w125">出生年</th>
            <th class="td_w100">男性<span class="font_12"></span></th>
          </tr>
        <tbody class="table_body">
          <tr>
            <td class="div_right"><%= @event_age.F1910.to_s(:delimited) %></td>
            <td class="">～1910</td>
            <td class="div_right"><%= @event_age.M1910.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1920.to_s(:delimited) %></td>
            <td class="">1920~1929</td>
            <td class="div_right"><%= @event_age.M1920.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1930.to_s(:delimited) %></td>
            <td class="">1930~1939</td>
            <td class="div_right"><%= @event_age.M1930.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1940.to_s(:delimited) %></td>
            <td class="">1940~1949</td>
            <td class="div_right"><%= @event_age.M1940.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1950.to_s(:delimited) %></td>
            <td class="">1950~1959</td>
            <td class="div_right"><%= @event_age.M1950.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1960.to_s(:delimited) %></td>
            <td class="">1960~1969</td>
            <td class="div_right"><%= @event_age.M1960.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1970.to_s(:delimited) %></td>
            <td class="">1970~1979</td>
            <td class="div_right"><%= @event_age.M1970.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1980.to_s(:delimited) %></td>
            <td class="">1980~1989</td>
            <td class="div_right"><%= @event_age.M1980.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F1990.to_s(:delimited) %></td>
            <td class="">1990~1999</td>
            <td class="div_right"><%= @event_age.M1990.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F2000.to_s(:delimited) %></td>
            <td class="">2000~2009</td>
            <td class="div_right"><%= @event_age.M2000.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="div_right"><%= @event_age.F2010.to_s(:delimited) %></td>
            <td class="">2010~</td>
            <td class="div_right"><%= @event_age.M2010.to_s(:delimited) %></td>
          </tr>
      </table>
    <% end %>
    <br/>
    <%# 男女年齢別end　%>

    <%# 居住地別begin　%>
    <% if @event_prefecture.present? %>
      <div><span class="div_bold">居住地別人口増減・移動</span></div>
      <table class="table_main inline-block head_color">
        <thead>
          <tr>
            <th colspan="2">北海道・東北</th>
            <th colspan="2">関東</th>
            <th colspan="2">中部</th>
            <th colspan="2">近畿</th>
            <th colspan="2">中国・四国</th>
            <th colspan="2">九州・沖縄</th>
          </tr>
        <tbody class="table_body">
          <tr>
            <td class="td_w75">北海道</td>
            <td class="td_w100 div_right"><%= @event_prefecture.Hokkaido.to_s(:delimited) %></td>
            <td class="td_w75">茨城県</td>
            <td class="td_w100 div_right"><%= @event_prefecture.Ibaraki.to_s(:delimited) %></td>
            <td class="td_w75">新潟県</td>
            <td class="td_w100 div_right"><%= @event_prefecture.Niigata.to_s(:delimited) %></td>
            <td class="td_w75">三重県</td>
            <td class="td_w100 div_right"><%= @event_prefecture.Mie.to_s(:delimited) %></td>
            <td class="td_w75">鳥取県</td>
            <td class="td_w100 div_right"><%= @event_prefecture.Tottori.to_s(:delimited) %></td>
            <td class="td_w75">福岡県</td>
            <td class="td_w100 div_right"><%= @event_prefecture.Fukuoka.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="">青森県</td>
            <td class="div_right"><%= @event_prefecture.Aomori.to_s(:delimited) %></td>
            <td class="">栃木県</td>
            <td class="div_right"><%= @event_prefecture.Tochigi.to_s(:delimited) %></td>
            <td class="">富山県</td>
            <td class="div_right"><%= @event_prefecture.Toyama.to_s(:delimited) %></td>
            <td class="">滋賀県</td>
            <td class="div_right"><%= @event_prefecture.Shiga.to_s(:delimited) %></td>
            <td class="">島根県</td>
            <td class="div_right"><%= @event_prefecture.Shimane.to_s(:delimited) %></td>
            <td class="">佐賀県</td>
            <td class="div_right"><%= @event_prefecture.Saga.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="">岩手県</td>
            <td class="div_right"><%= @event_prefecture.Iwate.to_s(:delimited) %></td>
            <td class="">群馬県</td>
            <td class="div_right"><%= @event_prefecture.Gunma.to_s(:delimited) %></td>
            <td class="">石川県</td>
            <td class="div_right"><%= @event_prefecture.Ishikawa.to_s(:delimited) %></td>
            <td class="">京都府</td>
            <td class="div_right"><%= @event_prefecture.Kyoto.to_s(:delimited) %></td>
            <td class="">岡山県</td>
            <td class="div_right"><%= @event_prefecture.Okayama.to_s(:delimited) %></td>
            <td class="">長崎県</td>
            <td class="div_right"><%= @event_prefecture.Nagasaki.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="">秋田県</td>
            <td class="div_right"><%= @event_prefecture.Akita.to_s(:delimited) %></td>
            <td class="">埼玉県</td>
            <td class="div_right"><%= @event_prefecture.Saitama.to_s(:delimited) %></td>
            <td class="">福井県</td>
            <td class="div_right"><%= @event_prefecture.Fukui.to_s(:delimited) %></td>
            <td class="">大阪府</td>
            <td class="div_right"><%= @event_prefecture.Osaka.to_s(:delimited) %></td>
            <td class="">広島県</td>
            <td class="div_right"><%= @event_prefecture.Hiroshima.to_s(:delimited) %></td>
            <td class="">熊本県</td>
            <td class="div_right"><%= @event_prefecture.Kumamoto.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="">宮城県</td>
            <td class="div_right"><%= @event_prefecture.Miyagi.to_s(:delimited) %></td>
            <td class="">千葉県</td>
            <td class="div_right"><%= @event_prefecture.Chiba.to_s(:delimited) %></td>
            <td class="">山梨県</td>
            <td class="div_right"><%= @event_prefecture.Yamanashi.to_s(:delimited) %></td>
            <td class="">兵庫県</td>
            <td class="div_right"><%= @event_prefecture.Hyogo.to_s(:delimited) %></td>
            <td class="">山口県</td>
            <td class="div_right"><%= @event_prefecture.Yamaguchi.to_s(:delimited) %></td>
            <td class="">大分県</td>
            <td class="div_right"><%= @event_prefecture.Oita.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="">山形県</td>
            <td class="div_right"><%= @event_prefecture.Yamagata.to_s(:delimited) %></td>
            <td class="">東京都</td>
            <td class="div_right"><%= @event_prefecture.Tokyo.to_s(:delimited) %></td>
            <td class="">長野県</td>
            <td class="div_right"><%= @event_prefecture.Nagano.to_s(:delimited) %></td>
            <td class="">奈良県</td>
            <td class="div_right"><%= @event_prefecture.Nara.to_s(:delimited) %></td>
            <td class="">徳島県</td>
            <td class="div_right"><%= @event_prefecture.Tokushima.to_s(:delimited) %></td>
            <td class="">宮崎県</td>
            <td class="div_right"><%= @event_prefecture.Miyazaki.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="">福島県</td>
            <td class="div_right"><%= @event_prefecture.Fukushima.to_s(:delimited) %></td>
            <td class="">神奈川県</td>
            <td class="div_right"><%= @event_prefecture.Kanagawa.to_s(:delimited) %></td>
            <td class="">岐阜県</td>
            <td class="div_right"><%= @event_prefecture.Gifu.to_s(:delimited) %></td>
            <td class="">和歌山県</td>
            <td class="div_right"><%= @event_prefecture.Wakayama.to_s(:delimited) %></td>
            <td class="">香川県</td>
            <td class="div_right"><%= @event_prefecture.Kagawa.to_s(:delimited) %></td>
            <td class="">鹿児島</td>
            <td class="div_right"><%= @event_prefecture.Kagoshima.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class=""></td>
            <td class=""></td>
            <td class=""></td>
            <td class=""></td>
            <td class="">静岡県</td>
            <td class="div_right"><%= @event_prefecture.Shizuoka.to_s(:delimited) %></td>
            <td class=""></td>
            <td class=""></td>
            <td class="">愛媛県</td>
            <td class="div_right"><%= @event_prefecture.Ehime.to_s(:delimited) %></td>
            <td class="">沖縄県</td>
            <td class="div_right"><%= @event_prefecture.Okinawa.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class=""></td>
            <td class=""></td>
            <td class=""></td>
            <td class=""></td>
            <td class="">愛知県</td>
            <td class="div_right"><%= @event_prefecture.Aichi.to_s(:delimited) %></td>
            <td class=""></td>
            <td class=""></td>
            <td class="">高知県</td>
            <td class="div_right"><%= @event_prefecture.Kochi.to_s(:delimited) %></td>
            <td class="">海外</td>
            <td class="div_right"><%= @event_prefecture.Others.to_s(:delimited) %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
    <%# 居住地別end　%>

  </div>

</div>

app/views/events/year_new.html.erb
<%= stylesheet_link_tag 'year_new' %>
<div class="body">
  <div class="div_center">
    <div>年別人口増減登録</div>
    <%= form_for @event,:url => {controller: "events", action: "year_create"} do |form| %>
      <table id="age_new_table" class="table_main inline-block">
              該当年
              <%= form.date_select  :date,
                  start_year: 2011, end_year: 2020,
                  use_month_numbers: true %>
      <div id="suibmit_btn">
        <%= form.submit value="男女・年齢別人口増減登録へ", data: {confirm: "該当年の年別人口増減データが上書きされます。よろしいですか?"} %>
      </div>
    <% end %>
  </div>
</div>